FROM python:3.13-slim

RUN apt-get update && apt-get install -y \
    ffmpeg \
    curl \
    && rm -rf /var/lib/apt/lists/* 

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/

ENV FFMPEG_PATH=ffmpeg \
    FFPROBE_PATH=ffprobe

# Prometheus metric 노출
EXPOSE 8001

CMD ["python", "-m", "app.worker.consumer"]